[workspace]
preview = ["pixi-build"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]


[dependencies]
python_rich = { path = "." }


[package]
name = "mcmc"
authors = ["Stéphane Despierres ,Pierre-Antoine Thouvenin"]
version = "1.0.0"
description = "A library to hepl building mcmc samplers. "

[package.build.backend]
name = "pixi-build-python"
version = "==0.4.0"

[package.host-dependencies]
hatchling = "*"

[package.run-dependencies]
rich = "13.9.*"
