#!/bin/bash
# Run the PSGLA within Split-Gibbs Sampler (SGS) over all datasets described
# in .json configuration files.
#
# author: pthouvenin (pierre-antoine.thouvenin@centralelille.fr)

# * Notes
#
# ! Parameter passed as explicit command line arguments override those from
# ! the configuration .json file
#
# ! This script can only be run once the synthetic data have been generated
# ! (see "generate_data.sh")
#
# ! BEWARE: running all the simulations below requires a large amount of space
# ! on the hard drive. All samples generated by the serial samplers
# ! are saved to disk in the form of multiple checkpoint files, from which the
# ! samplers can be restarted to obtain a longer chain)

# * Configuring the experiments

# mode to run the experiments, either "serial", "gpu", "distributed" or "multi_gpu"
mode="distributed"
ncores=2

# deactivate JIT compilation for fair comparison with C++
# export NUMBA_NUM_THREADS=1
# export NUMBA_DISABLE_JIT=1

# list of configuration files for the experiments
declare -a experiments_configs=("gaussian_deconvolution_house_isnr40_ks3.json")
# "config_cameraman_benchmark.json"


# * Running experiments

case $mode in

    # single cpu
    "serial")
        command=python
        ncores=1
        ;;

    # single gpu
    "gpu")
        command=python
        ncores=1
        ;;

    # multiple cpus
    "distributed")
        command="mpiexec -n ${ncores} python -m mpi4py"
        ;;

    *)
        echo "Unknown mode selected, default "serial"  mode considered"
        command=python
        mode="serial"
        ncores=1
        ;;
esac

# pixi shell # remove is project not managed with pixi

# loop over configuration files
for configfile in "${experiments_configs[@]}"; do
    echo Experiment: mode=${mode}, config=${configfile}, ncores=${ncores};

    ${command} main.py \
    --config=${configfile} \
    --mode=${mode}
done

# exit
