"""Utility functions to analyze generated data."""

# authors: M. Bouton, S. Despierres, P.-A. Thouvenin, P. Chainais
#
# reference: M. Bouton, P.-A. Thouvenin, A. Repetti, P. Chainais - **A
# Distributed Plug-and-Play MCMC Algorithm for High-Dimensional Inverse
# Problems**, [arxiv preprint](http://arxiv.org/abs/), October 2025.

# TODO: revise implementation of display functions, move to an auxiliary module separate from torch-related utilities

import json
from os.path import join
from typing import Any, Optional, Sequence

import h5py
import matplotlib.pyplot as plt
import numpy as np
import torch

from cards.backend import xp
from cards.utils.metrics import snr, ssim


def extract_subset_from_dict(d: dict[str, Any], keys: Sequence[str]) -> dict[str, Any]:
    """Extracts a subset of a dictionary based on the provided keys.

    Parameters
    ----------
    d : dict[str, Any]
        The original dictionary.
    keys : Sequence[str]
        The keys to extract.

    Returns
    -------
    dict
        A new dictionary containing only the specified keys and their values.
    """
    return {key: d[key] for key in keys}


def expand_shape_left(original_shape: Sequence[int], ndim: int) -> tuple[int, ...]:
    """Expand a shape to a specified number of dimensions on the left.

    Parameters
    ----------
    original_shape : Sequence[int]
        The original shape of the array.
    ndim : int
        The desired number of dimensions.

    Returns
    -------
    tuple[int,...]
        The expanded shape with the specified number of dimensions.
    """
    if len(original_shape) >= ndim:
        return tuple(original_shape)
    return (1,) * (ndim - len(original_shape)) + tuple(original_shape)


def expanded_left_view(array: xp.ndarray, ndim: int) -> xp.ndarray:
    """Expand the shape of an array to a specified number of dimensions on the left.

    Parameters
    ----------
    array : xp.ndarray
        The original array.
    ndim : int
        The desired number of dimensions.

    Returns
    -------
    xp.ndarray
        The expanded array with the specified number of dimensions.

    Notes
    -----
    This function uses broadcasting to expand the shape of the array without copying data.
    """

    if array.ndim >= ndim:
        return array
    return xp.broadcast_to(array, expand_shape_left(array.shape, ndim))


def xp2torch(x: xp.ndarray, add_batch: bool = True, torch_dtype=None):
    """Convert a ndarray to a PyTorch tensor.

    Parameters
    ----------
    x : xp.ndarray
        ndarray array to be converted.
    add_batch : bool, optional
        If True, add a batch dimension to the tensor (default is True).

    Returns
    -------
    torch.Tensor
        PyTorch tensor.
    """
    return torch.as_tensor(x[None, :] if add_batch else x).to(torch_dtype)


def torch2xp(x: torch.Tensor, remove_batch: bool = True, cp_dtype=None):
    """Convert a PyTorch tensor to a ndarray.

    Parameters
    ----------
    x : torch.Tensor
        PyTorch tensor to be converted.
    remove_batch : bool, optional
        If True, remove the batch dimension from the array (default is True).

    Returns
    -------
    xp.ndarray
        Converted ndarray.
    """
    return xp.asarray((x.squeeze(0) if remove_batch else x).detach(), dtype=cp_dtype)


def array_to_plt_img(arr: np.ndarray):
    return np.moveaxis(arr, 0, -1)


def plot_results(
    observations: np.ndarray,
    original: np.ndarray,
    MMSE: np.ndarray,
    potential: np.ndarray,
    dynamic_range: float = 1.0,
    slices: slice = slice(None),
    enable_save: bool = False,
    save_path: Optional[str] = None,
):
    """Plot the data generated by a "compute" function : the reconstruction, the absolute error and the potential.

    Parameters
    ----------
    observations : np.ndarray
        Deteriorated signal.
    original : np.ndarray
        Original signal without any loss or noise.
    MMSE : np.ndarray
        Approximation of the original signal.
    potential : np.ndarray
        Historic of the potential for each step of the Markov chain.
    slices : slice
        Select which portion of the observation must be compared to the original.
    enable_save : bool
        Activate or deactivate the save of the printed figures.
    save_path :
        Path to the directory where we will save the figures.
    """

    pixelMin = np.min(original)
    pixelMax = np.max(original)

    plt.figure()
    plt.imshow(original.T, vmin=pixelMin, vmax=pixelMax)
    plt.title("Truth")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(observations.T / dynamic_range, vmin=pixelMin, vmax=pixelMax)
    plt.title("Observations")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(MMSE.T, vmin=pixelMin, vmax=pixelMax)
    plt.title("MMSE")
    plt.colorbar()
    if enable_save:
        name = join(save_path, "reconstruction.pdf")
        if len(MMSE.shape) > 2:
            plt.imsave(
                name,
                arr=array_to_plt_img(MMSE),
                vmin=pixelMin,
                vmax=pixelMax,
                format="pdf",
            )  #! incorrect format 3*M*N -> M*N*3 for plt.imsave
        else:
            plt.imsave(name, arr=MMSE, vmin=pixelMin, vmax=pixelMax, format="pdf")
    plt.show()

    plt.figure()
    plt.imshow(np.abs(original[slices].T - MMSE.T))
    plt.title("Absolute error Truth/Estimator")
    plt.colorbar()
    if enable_save:
        name = join(save_path, "error.pdf")
        if len(MMSE.shape) > 2:
            plt.imsave(
                name,
                arr=array_to_plt_img((np.abs(original[slices] - MMSE))),
                vmin=pixelMin,
                vmax=pixelMax,
                format="pdf",
            )
        else:
            plt.imsave(
                name,
                arr=(np.abs(original[slices] - MMSE)),
                vmin=pixelMin,
                vmax=pixelMax,
                format="pdf",
            )
    plt.show()

    plt.figure()
    plt.plot(potential)
    plt.title("Potential")
    plt.grid()
    if enable_save:
        name = join(save_path, "potential.pdf")
        plt.savefig(name, format="pdf")
    plt.show()


def analyze_data(
    n_checkpoint: int,
    checkpoint_size: int,
    burnin: int,
    save_path: str,
    obs_path: str,
    output_file_name: str,
    dynamic_range: float = 1.0,
    slices: slice = slice(None),
    comm_size: int = 0,
    save_picture: bool = False,
    show_results=True,
) -> None:
    """Read the sample produced by a "compute" function and make some metrics out of it.

    Parameters
    ----------
    n_checkpoint : int
        Number of batches of the sample.
    checkpoint_size: int
        Number of steps between two checkpoints.
    batch_size: int
        Size of the batches.
    burnin : int
        Number of bacth to ignore to take into account the burn-in.
    save_path : str
        Path to the directory where the sample has been saved.
    obs_path : str
        Path to the file containing the deteriorated signal.
    output_file_name : str
        Full path to the file on which we will write the metrics.
    slices : slice
        Select which portion of the observation must be compared to the original.
    comm_size : int
        Number of process, must be used only in a distributed setting.
    comm_size : int
        Number of process, must be used only in a distributed setting.
    """

    potential = np.zeros([n_checkpoint * checkpoint_size])
    if comm_size == 0:
        time = np.zeros([n_checkpoint * checkpoint_size])
    else:
        time = np.zeros([comm_size, n_checkpoint * checkpoint_size])

    for i in range(1, n_checkpoint + 1):
        file_name = join(save_path, "sample" + str(i) + ".h5")

        with h5py.File(file_name, "r") as file:
            potential[(i - 1) * checkpoint_size : i * checkpoint_size] = file[
                "potential"
            ][:]
            if comm_size != 0:
                time[:, (i - 1) * checkpoint_size : i * checkpoint_size] = file[
                    "computation_time"
                ][:]
            else:
                time[(i - 1) * checkpoint_size : i * checkpoint_size] = file[
                    "computation_time"
                ][:]

    atime = np.asarray(np.mean(time, axis=-1))
    time_std = np.asarray(np.std(time, axis=-1))

    with h5py.File(obs_path, "r") as file:
        original = file["x"][:]
        observations = file["y"][:]

    MMSE = np.zeros(original.shape)
    for i in range(burnin, n_checkpoint):
        file_name = join(save_path, "sample" + str(i) + ".h5")
        with h5py.File(file_name, "r") as file:
            MMSE += file["MMSE"]
    MMSE /= n_checkpoint - burnin

    snr_obs = snr(original, observations[slices] / dynamic_range)
    snr_recons = snr(original, MMSE)

    ssim_obs = ssim(original, observations[slices] / dynamic_range)
    ssim_recons = ssim(original, MMSE)

    results = {
        "atime": atime.tolist(),
        "std_time": time_std.tolist(),
        "snr_obs": float(snr_obs),
        "snr_recons": float(snr_recons),
        "ssim_obs": float(ssim_obs),
        "ssim_recons": float(ssim_recons),
    }  # float32 -> float64
    results_json = json.dumps(results)

    results_file = join(save_path, output_file_name + ".json")
    with open(results_file, "w") as file:
        file.write(results_json)

    if show_results:
        plot_results(
            observations,
            original,
            MMSE,
            potential,
            dynamic_range,
            enable_save=save_picture,
            save_path=save_path,
        )
