import json
import logging
import pathlib
from os.path import exists, join, splitext

import cupy as cp
import h5py
import matplotlib.pyplot as plt
import numpy as np
import scipy
from skimage.metrics import structural_similarity as ssim

from mcmc.models.GaussianDeconvolutionModel import GaussianDeconvolutionModel
from mcmc.models.GpuGaussianDeconvolutionModel import GpuGaussianDeconvolutionModel
from mcmc.operators.serial_convolution import fft_conv
from mcmc.sampler.GpuSampler import GpuSampler
from mcmc.sampler.SerialSampler import Sampler
from mcmc.TransitionKernel.GpuTransitionKernel import GpuPSGLA
from mcmc.TransitionKernel.TransitionKernel import PSGLA


def load_from_h5(filename):
    """load the mask01, sig2 and data entries from the h5 file"""
    with h5py.File(filename, "r") as data_file:
        kernel = data_file["kernel"][:]
        sigma2 = data_file["sig2"][()]
        observations = data_file["data"][:]
    return kernel, sigma2, observations


def compute_step_size(split_coef: float, sigma2: float, kernel: np.ndarray):
    x = 0.99 / (8.0 / split_coef + np.max(np.abs(np.fft.rfft2(kernel))) ** 2 / sigma2)
    z = 0.99 * split_coef
    return (x, z)


def generate_gaussian_kernel(kernel_size, kernel_std) -> np.ndarray:
    r"""Generate a square normalized 2D Gaussian kernel.

    Parameters
    ----------
    kernel_size : int
        Size of one dimension of the kernel.
    kernel_std : float
        Standard deviation of the Gaussian kernel.

    Note
    ----
    Equivalent to the ``fspecial('gaussian', ...)`` function in Matlab.

    Returns
    -------
    h : numpy.ndarray
        Square Gaussian kernel with :math:`\|h\|_1 = 1`.
    """
    # equivalent to fspecial('gaussian', ...) in Matlab
    w = scipy.signal.windows.gaussian(kernel_size, kernel_std)
    h = w[:, np.newaxis] * w[np.newaxis, :]
    h = h / np.sum(h)
    return h


# TODO: rewrite as a generic function or class, using measurement operator objects and lambda function to imject noise
# TODO: extract image loading and normalization, take as a helper function
def generate_observations(
    original_path: str,
    kernel_dims: np.ndarray,
    kernel_std: float,
    snr: float,
    data_seed: int,
    obs_path: str,
    maximum: float = 1.0,
) -> None:
    filename, file_extension = splitext(original_path)

    if file_extension == ".h5":
        with h5py.File(original_path) as file:
            img = file["x"][:]
    else:
        from PIL import Image

        img = np.asarray(Image.open(original_path, "r")).astype(np.double)

    # rescaling image linearly from [min(img), max(img)] to prescribed range [0, maximum]
    a = 0.0
    b = maximum
    img = a + (b - a) * (img - np.min(img)) / (np.max(img) - np.min(img))

    kernel = generate_gaussian_kernel(kernel_dims, kernel_std)

    fft_dims = np.asarray(img.shape) + kernel_dims - np.ones(2, dtype=int)
    blurred = fft_conv(img, np.fft.rfft2(kernel, fft_dims), fft_dims)

    sigma2 = np.linalg.norm(img) ** 2 / blurred.size / (10 ** (snr / 10))
    # sigma2 = 10 ** (-snr / 10) * np.var(blurred)

    rng = np.random.default_rng(data_seed)
    observations = blurred + np.sqrt(sigma2) * rng.standard_normal(size=blurred.shape)

    with h5py.File(obs_path, "w") as file:
        file["kernel"] = kernel
        file["data"] = observations
        file["sig2"] = sigma2
        file["x"] = img
        file["N"] = np.asarray(img.shape, dtype=int)
        file["data_seed"] = np.asarray([data_seed], dtype=int)


# TODO: save figures produced to be visualized later
def plot_results(
    observations: np.ndarray,
    original: np.ndarray,
    MMSE: np.ndarray,
    potential: np.ndarray,
) -> None:
    """plot_results Plot the data generated by a "compute" function : the reconstruction, the absolute error and the potential.

    Parameters
    ----------
    observations : np.ndarray
        Degraded signal.
    original : np.ndarray
        Original signal without any loss or noise.
    MMSE : np.ndarray
        Approximation of the original signal.
    potential : np.ndarray
        Historic of the potential for each step of the Markov chain.
    """

    pixelMin = 0.0
    pixelMax = 1.0

    original = original / np.amax(original)

    plt.figure()
    plt.imshow(original.T, cmap="gray", vmin=pixelMin, vmax=pixelMax)
    plt.title("Truth")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(observations.T, cmap="gray", vmin=pixelMin, vmax=pixelMax)
    plt.title("Observations")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(MMSE.T, cmap="gray", vmin=pixelMin, vmax=pixelMax)
    plt.title("MMSE")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(np.abs(original.T - MMSE.T), cmap="gray")
    plt.title("Absolute error Truth/Estimator")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.plot(potential)
    plt.title("Potential")
    plt.grid()
    plt.show()


def analyze_data(
    nb_batches: int,
    burnin: int,
    save_path: str,
    data_path: str,
    output_file_name: str,
) -> None:
    potential = []
    time = []
    for i in range(1, nb_batches + 1):
        file_name = join(save_path, "sample" + str(i) + ".h5")

        with h5py.File(file_name, "r") as file:
            potential = np.append(potential, file["potential"][:])
            time = np.append(time, file["computation_time"][:])

    atime = np.mean(time)
    total_time = np.sum(time)
    time_std = np.std(time)

    with h5py.File(data_path, "r") as file:
        original = file["x"][:]
        observations = file["data"][:]

    MMSE = np.zeros(original.shape)
    for i in range(burnin, nb_batches):
        file_name = join(save_path, "sample" + str(i) + ".h5")
        with h5py.File(file_name, "r") as file:
            MMSE += file["MMSE"]
    MMSE /= nb_batches - burnin

    M, N = original.shape
    Mm, Nn = observations.shape
    m = Mm - M + 1
    n = Nn - N + 1

    original /= np.amax(original)

    snr_obs = 10 * np.log10(
        np.linalg.norm(original) ** 2
        / (
            np.linalg.norm(
                original - observations[m // 2 : M + m // 2, n // 2 : N + n // 2]
            )
            ** 2
        )
    )

    snr_recons = 10 * np.log10(
        np.linalg.norm(original) ** 2 / (np.linalg.norm(original - MMSE) ** 2)
    )

    ssim_obs = ssim(
        original,
        observations[m // 2 : M + m // 2, n // 2 : N + n // 2],
        data_range=np.amax(original) - np.amin(original),
    )
    ssim_recons = ssim(original, MMSE, data_range=np.amax(original) - np.amin(original))

    results = {
        "atime": atime,
        "total_time": total_time,
        "std_time": time_std,
        "snr_obs": snr_obs,
        "snr_recons": snr_recons,
        "ssim_obs": ssim_obs,
        "ssim_recons": ssim_recons,
    }
    results_json = json.dumps(results)

    results_file = join(save_path, output_file_name + ".json")
    with open(results_file, "w") as file:
        file.write(results_json)

    plot_results(observations, original, MMSE, potential)


def compute_serial(
    logger: logging.Logger,
    kernel: np.ndarray,
    split_coef: float,
    reg_coef: float,
    batch_size: int,
    nb_batches: int,
    seed: int,
    save_path: str,
    data_path: str,
):
    r"""compute_serial Generate a sample withe the serial implementation.

    Parameters
    ----------
    logger: logging.Logger
        Logger object.
    split_coef : float
        Splitting coefficient, parameter of the model.
    reg_coef : float
        Regularization coefficient, parameter of the model.
    batch_size : float
        Number of iterations for a batch.
    nb_batches : int
        Number of batches of the sample.
    seed : int
        Seed.
    save_path : str
        Path to the directory where we will save the sample.
    data_path : str
        Path to the file containing the deteriorated signal.
    """

    kernel, sigma2, observations = load_from_h5(data_path)

    step_size_X, step_size_Z = compute_step_size(split_coef, sigma2, kernel)

    Mm, Nn = observations.shape
    m, n = kernel.shape
    M = Mm - m + 1
    N = Nn - n + 1
    X = PSGLA(np.asarray([M, N], dtype=int), step_size_X)
    Z = PSGLA((2, *X.current_state.shape), step_size_Z)

    model = GaussianDeconvolutionModel(
        observations, kernel, X, Z, sigma2, reg_coef, split_coef
    )

    sampler = Sampler(batch_size, nb_batches, seed, "sample", save_path, model, logger)

    sampler.sample()


def compute_gpu(
    logger: logging.Logger,
    kernel: np.ndarray,
    split_coef: float,
    reg_coef: float,
    batch_size: int,
    nb_batches: int,
    seed: int,
    save_path: str,
    data_path: str,
):
    r"""compute_serial Generate a sample withe the serial implementation.

    Parameters
    ----------
    logger: logging.Logger
        Logger object.
    split_coef : float
        Splitting coefficient, parameter of the model.
    reg_coef : float
        Regularization coefficient, parameter of the model.
    batch_size : float
        Number of iterations for a batch.
    nb_batches : int
        Number of batches of the sample.
    seed : int
        Seed.
    save_path : str
        Path to the directory where we will save the sample.
    data_path : str
        Path to the file containing the deteriorated signal.
    """

    kernel, sigma2, observations = load_from_h5(data_path)

    step_size_X, step_size_Z = compute_step_size(split_coef, sigma2, kernel)

    Mm, Nn = observations.shape
    m, n = kernel.shape
    M = Mm - m + 1
    N = Nn - n + 1
    X = GpuPSGLA(np.asarray([M, N], dtype=int), step_size_X)
    Z = GpuPSGLA((2, *X.current_state.shape), step_size_Z)

    model = GpuGaussianDeconvolutionModel(
        cp.asarray(observations), cp.asarray(kernel), X, Z, sigma2, reg_coef, split_coef
    )

    sampler = GpuSampler(
        batch_size, nb_batches, seed, "sample", save_path, model, logger
    )

    sampler.sample()


def main(mode, config_file_name):
    config_file = open(config_file_name)
    params = json.load(config_file)

    args = {
        "nb_batches": params["nbCheckpoint"],
        "batch_size": params["sampleSize"],
        "save_path": params["savePath"],
        "split_coef": params["alpha"],
        "reg_coef": params["regularizationCoefficient"],
        "seed": params["seed"],
        "data_path": params["dataPath"],
    }

    args_analysis = {
        "nb_batches": params["nbCheckpoint"],
        "burnin": params["burnin"],
        "save_path": params["savePath"],
        "data_path": params["dataPath"],
    }

    # FIXME: rewrite to obtain a main file mostly independent of the application considered
    if not exists(args["data_path"]):
        generate_observations(
            params["originPath"],
            params["kernel_size"],
            params["kernel_std"],
            params["isnr"],
            params["data_seed"],
            params["dataPath"],
        )

    with h5py.File(params["dataPath"]) as file:
        kernel = file["kernel"][:]

    if mode == "serial":
        pathlib.Path(params["savePath"]).mkdir(parents=True, exist_ok=True)
        logger = logging.getLogger(__name__)
        logging.basicConfig(
            filename=params["logFilename"],
            level=logging.INFO,
            filemode="w",
            format="%(asctime)s %(levelname)s %(message)s",
        )
        compute_serial(logger=logger, kernel=kernel, **args)
        analyze_data(**args_analysis, output_file_name="results_gaussian_deconv_serial")

    if mode == "gpu":
        pathlib.Path(params["savePath"]).mkdir(parents=True, exist_ok=True)
        logger = logging.getLogger(__name__)
        logging.basicConfig(
            filename=params["logFilename"],
            level=logging.INFO,
            filemode="w",
            format="%(asctime)s %(levelname)s %(message)s",
        )
        compute_gpu(logger=logger, kernel=kernel, **args)
        analyze_data(**args_analysis, output_file_name="results_gaussian_deconv_gpu")


if __name__ == "__main__":
    main(mode="serial", config_file_name="config_house.json")
    # main(mode="gpu", config_file_name="config_cameraman.json")
    # main(mode="distributed", config_file_name="config_cameraman.json")

# mpirun -n 9 python -m mpi4py main.py
