import numpy as np
from os.path import join, splitext
import h5py
from mcmc.operators.linear_operator import LinearOperator
import matplotlib.pyplot as plt
from skimage.metrics import structural_similarity as ssim
import json


def load_args_from_json(config_file_path: str) -> dict:
    config_file = open(config_file_path)
    params = json.load(config_file)

    args = {
        "nb_batches": params["nbCheckpoint"],
        "batch_size": params["sampleSize"],
        "save_path": params["savePath"],
        "seed": params["seed"],
        "data_path": params["dataPath"],
    }
    return args


def load_args_analysis_from_json(config_file_path: str) -> dict:
    config_file = open(config_file_path)
    params = json.load(config_file)

    args_analysis = {
        "nb_batches": params["nbCheckpoint"],
        "batch_size": params["sampleSize"],
        "burnin": params["burnin"],
        "save_path": params["savePath"],
        "data_path": params["dataPath"],
    }
    return args_analysis


def normalize_img(img: np.ndarray, maximum: float = 1.0) -> np.ndarray:
    a = 0.0
    b = maximum
    return a + (b - a) * (img - np.min(img)) / (np.max(img) - np.min(img))


def load_img(path: str) -> np.ndarray:
    filename, file_extension = splitext(path)

    if file_extension == ".h5":
        with h5py.File(path) as file:
            img = np.asarray(file["x"][:])
    else:
        from PIL import Image

        img = np.asarray(Image.open(path, "r")).astype(np.double)

    return img


def load_img_size(path: str) -> np.ndarray:
    filename, file_extension = splitext(path)

    if file_extension == ".h5":
        with h5py.File(path) as file:
            img = np.asarray(file["x"][:])
            return img.shape
    else:
        from PIL import Image

        img = np.asarray(Image.open(path, "r")).astype(np.double)
        return img.shape


def apply_gaussian_noise(
    signal: np.ndarray, snr: float, rng: np.random.Generator
) -> list[np.ndarray, dict]:  # not a list but a union
    param = {}
    sigma2 = np.linalg.norm(signal) ** 2 / signal.size / (10 ** (snr / 10))
    param["sigma2"] = sigma2
    return signal + rng.normal(
        loc=np.zeros_like(signal), scale=np.sqrt(sigma2), size=signal.shape
    ), param


def generate_observations(
    original_path: str,
    operator: LinearOperator,
    snr: float,
    apply_noise: callable,
    data_seed: int,
    obs_path: str,
    problem_parameters: dict = None,
    maximum: float = 1.0,
) -> None:
    """generate_observations Generates and saves a deteriorated signal from the one given in entry.

    Parameters
    ----------
    original_path : str
        Path to the file containing the ground truth.
    operator : LinearOperator
        Determinist deterioration operator.
    snr : float
        Noise level for the generated data.
    data_seed : int
        Seed.
    obs_path : str
        Path to the file where to save the generated data.
    problem_parameters : dict, optional
        Dictionnary containing problem specific parameters to be saved with the data, by default None
    maximum : float, optional
        Maximum value imposed for the ground truth image used to generate synthetic data.
    """

    img = load_img(original_path)
    # rescaling image linearly from [min(img), max(img)] to prescribed range [0, maximum]
    img = normalize_img(img, maximum=maximum)

    rng = np.random.default_rng(data_seed)

    buffer = operator.forward(img)
    observations, noise_param = apply_noise(buffer, snr, rng)

    problem_parameters.update(noise_param)

    with h5py.File(obs_path, "w") as file:
        file["x"] = img
        file["data"] = observations
        file["N"] = np.asarray(img.shape, dtype=int)
        file["data_seed"] = np.asarray([data_seed], dtype=int)

        if problem_parameters is not None:
            for key in problem_parameters.keys():
                file[key] = problem_parameters[key]


def plot_results(
    observations: np.ndarray,
    original: np.ndarray,
    MMSE: np.ndarray,
    potential: np.ndarray,
    slices: slice = slice(None),
    enable_save: bool = False,
    save_path: str = None,
) -> None:
    """plot_results Plot the data generated by a "compute" function : the reconstruction, the absolute error and the potential.

    Parameters
    ----------
    observations : np.ndarray
        Deteriorated signal.
    original : np.ndarray
        Original signal without any loss or noise.
    MMSE : np.ndarray
        Approximation of the original signal.
    potential : np.ndarray
        Historic of the potential for each step of the Markov chain.
    slices : slice
        Select which portion of the observation must be compared to the original.
    enable_save : bool
        Activate or deactivate the save of the printed figures.
    save_path :
        Path to the directory where we will save the figures.
    """

    # if not (original.shape == observations.shape) and slices == slice(None):
    #     raise ValueError(
    #         "Image and observations don't have the same dimensions. Indicate which part of observations must be selected."
    #     )

    pixelMin = np.min(original)
    pixelMax = np.max(original)

    plt.figure()
    plt.imshow(original.T, cmap="gray", vmin=pixelMin, vmax=pixelMax)
    plt.title("Truth")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(observations.T, cmap="gray", vmin=pixelMin, vmax=pixelMax)
    plt.title("Observations")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(MMSE.T, cmap="gray", vmin=pixelMin, vmax=pixelMax)
    plt.title("MMSE")
    plt.colorbar()
    if enable_save:
        name = join(save_path, "reconstruction")
        plt.imsave(name, arr=MMSE, vmin=pixelMin, vmax=pixelMax, format="pdf")
    plt.show()

    plt.figure()
    plt.imshow(np.abs(original[slices].T - MMSE.T), cmap="gray")
    plt.title("Absolute error Truth/Estimator")
    plt.colorbar()
    if enable_save:
        name = join(save_path, "error")
        plt.imsave(
            name,
            arr=(np.abs(original[slices] - MMSE)),
            vmin=pixelMin,
            vmax=pixelMax,
            format="pdf",
        )
    plt.show()

    plt.figure()
    plt.plot(potential)
    plt.title("Potential")
    plt.grid()
    if enable_save:
        name = join(save_path, "potential")
        plt.savefig(name, format="pdf")
    plt.show()


def analyze_data(
    nb_batches: int,
    batch_size: int,
    burnin: int,
    save_path: str,
    data_path: str,
    output_file_name: str,
    slices: slice = slice(None),
    comm_size: int = 0,
    save_picture: bool = False,
) -> None:
    """analyze_data Read the sample produced by a "compute" function and make some metrics out of it.

    Parameters
    ----------
    nb_batches : int
        Number of batches of the sample.
    batch_size: int
        Size of the batches.
    burnin : int
        Number of bacth to ignore to take into account the burn-in.
    save_path : str
        Path to the directory where the sample has been saved.
    data_path : str
        Path to the file containing the deteriorated signal.
    output_file_name : str
        Full path to the file on which we will write the metrics.
    slices : slice
        Select which portion of the observation must be compared to the original.
    comm_size : int
        Number of process, must be used only in a distributed setting.
    """

    potential = np.zeros([nb_batches * batch_size])
    if comm_size == 0:
        time = np.zeros([nb_batches * batch_size])
        batch_time = np.zeros([nb_batches])
    else:
        time = np.zeros([comm_size, nb_batches * batch_size])
        batch_time = np.zeros([comm_size, nb_batches])

    for i in range(1, nb_batches + 1):
        file_name = join(save_path, "sample" + str(i) + ".h5")

        with h5py.File(file_name, "r") as file:
            potential[(i - 1) * batch_size : i * batch_size] = file["potential"][:]
            if comm_size != 0:
                time[:, (i - 1) * batch_size : i * batch_size] = file[
                    "computation_time"
                ][:]
                batch_time[:, i - 1] = file["batch_time"][:]
            else:
                time[(i - 1) * batch_size : i * batch_size] = file["computation_time"][
                    :
                ]
                batch_time[i - 1] = file["batch_time"][:]

    # FIXME - time metrics unfit for distributed implementation
    atime = np.asarray(np.mean(time, axis=-1))
    total_time = np.asarray(np.sum(batch_time, axis=-1))
    time_std = np.asarray(np.std(time, axis=-1))

    with h5py.File(data_path, "r") as file:
        original = file["x"][:]
        observations = file["data"][:]

    # if not (original.shape == observations.shape) and slices == slice(None):
    #     raise ValueError(
    #         "Image and observations don't have the same dimensions. Indicate which part of observations must be selected."
    #     )

    MMSE = np.zeros(original.shape)
    for i in range(burnin, nb_batches):
        file_name = join(save_path, "sample" + str(i) + ".h5")
        with h5py.File(file_name, "r") as file:
            MMSE += file["MMSE"]
    MMSE /= nb_batches - burnin

    snr_obs = 10 * np.log10(
        np.linalg.norm(original) ** 2
        / (np.linalg.norm(original - observations[slices]) ** 2)
    )

    snr_recons = 10 * np.log10(
        np.linalg.norm(original) ** 2 / (np.linalg.norm(original - MMSE) ** 2)
    )

    ssim_obs = ssim(
        original, observations[slices], data_range=np.max(original) - np.min(original)
    )
    ssim_recons = ssim(original, MMSE, data_range=np.max(original) - np.min(original))

    results = {
        "atime": atime.tolist(),
        "total_time": total_time.tolist(),
        "std_time": time_std.tolist(),
        "snr_obs": snr_obs,
        "snr_recons": snr_recons,
        "ssim_obs": ssim_obs,
        "ssim_recons": ssim_recons,
    }
    results_json = json.dumps(results)

    results_file = join(save_path, output_file_name + ".json")
    with open(results_file, "w") as file:
        file.write(results_json)

    plot_results(
        observations,
        original,
        MMSE,
        potential,
        enable_save=save_picture,
        save_path=save_path,
    )
