import gc
import json
from pathlib import Path
from typing import Any, Callable, Sequence

import cupy as cp
import h5py
import matplotlib.pyplot as plt
import numpy as np
import torch

from mcmc.backend import xp
from mcmc.utils.metrics import psnr, snr, ssim


def extract_subset_from_dict(d: dict[str, Any], keys: Sequence[str]) -> dict[str, Any]:
    """Extracts a subset of a dictionary based on the provided keys.

    Parameters
    ----------
    d : dict[str, Any]
        The original dictionary.
    keys : Sequence[str]
        The keys to extract.

    Returns
    -------
    dict
        A new dictionary containing only the specified keys and their values.
    """
    return {key: d[key] for key in keys}


def expand_shape_left(original_shape: tuple[int, ...], ndim: int) -> tuple[int, ...]:
    """Expand a shape to a specified number of dimensions on the left.

    Parameters
    ----------
    original_shape : tuple[int,...]
        The original shape of the array.
    ndim : int
        The desired number of dimensions.

    Returns
    -------
    tuple[int,...]
        The expanded shape with the specified number of dimensions.
    """
    if len(original_shape) >= ndim:
        return original_shape
    return (1,) * (ndim - len(original_shape)) + original_shape


def expanded_left_view(array: xp.ndarray, ndim: int) -> xp.ndarray:
    """Expand the shape of an array to a specified number of dimensions on the left.

    Parameters
    ----------
    array : xp.ndarray
        The original array.
    ndim : int
        The desired number of dimensions.

    Returns
    -------
    xp.ndarray
        The expanded array with the specified number of dimensions.

    Notes
    -----
    This function uses broadcasting to expand the shape of the array without copying data.
    """

    if array.ndim >= ndim:
        return array
    return xp.broadcast_to(array, expand_shape_left(array.shape, ndim))


def xp2torch(x: xp.ndarray, add_batch: bool = True):
    """
    Convert a ndarray to a PyTorch tensor.

    Parameters
    ----------
    x : xp.ndarray
        ndarray array to be converted.
    add_batch : bool, optional
        If True, add a batch dimension to the tensor (default is True).

    Returns
    -------
    torch.Tensor
        PyTorch tensor.
    """
    return torch.as_tensor(x[None, :] if add_batch else x)


def torch2xp(x: torch.Tensor, remove_batch: bool = True):
    """
    Convert a PyTorch tensor to a ndarray.

    Parameters
    ----------
    x : torch.Tensor
        PyTorch tensor to be converted.
    remove_batch : bool, optional
        If True, remove the batch dimension from the array (default is True).

    Returns
    -------
    xp.ndarray
        Converted ndarray.
    """
    return xp.asarray((x.squeeze(0) if remove_batch else x).detach())


def plot_results(
    observations: np.ndarray,
    original: np.ndarray,
    MMSE: np.ndarray,
    potential: np.ndarray,
    slices: slice = slice(None),
    enable_save: bool = False,
    save_path: str = None,
) -> None:
    """Plot the data generated by a "compute" function : the reconstruction, the absolute error and the potential.

    Parameters
    ----------
    observations : np.ndarray
        Deteriorated signal.
    original : np.ndarray
        Original signal without any loss or noise.
    MMSE : np.ndarray
        Approximation of the original signal.
    potential : np.ndarray
        Historic of the potential for each step of the Markov chain.
    slices : slice
        Select which portion of the observation must be compared to the original.
    enable_save : bool
        Activate or deactivate the save of the printed figures.
    save_path :
        Path to the directory where we will save the figures.
    """

    val_min = np.min(original)
    val_max = np.max(original)

    cmap = plt.get_cmap("gray") if len(original.shape) == 2 else None

    plt.figure()
    plt.imshow(original, cmap=cmap, vmin=val_min, vmax=val_max)
    plt.title("Truth")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(observations, cmap=cmap, vmin=val_min, vmax=val_max)
    plt.title("Observations")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(MMSE, cmap=cmap, vmin=val_min, vmax=val_max)
    plt.title("MMSE")
    plt.colorbar()
    if enable_save:
        name = join(save_path, "reconstruction.pdf")
        plt.imsave(name, arr=MMSE, vmin=val_min, vmax=val_max, format="pdf")
    plt.show()

    plt.figure()
    plt.imshow(np.abs(original[slices] - MMSE), cmap=cmap)
    plt.title("Absolute error Truth/Estimator")
    plt.colorbar()
    if enable_save:
        name = join(save_path, "error.pdf")
        plt.imsave(
            name,
            arr=(np.abs(original[slices] - MMSE)),
            vmin=val_min,
            vmax=val_max,
            format="pdf",
        )
    plt.show()

    plt.figure()
    plt.plot(potential)
    plt.title("Potential")
    plt.grid()
    if enable_save:
        name = Path(save_path) / "potential.pdf"
        plt.savefig(name, format="pdf")
    plt.show()


def analyze_data(
    n_checkpoint: int,
    checkpoint_size: int,
    burnin: int,
    save_path: str,
    obs_path: str,
    output_file_name: str,
    slices: slice = slice(None),
    comm_size: int = 1,
    obs_rg: int = 1,
) -> None:
    """
    Analyze the results of MCMC sampling and compute reconstruction metrics.

    Parameters
    ----------
    n_checkpoint : int
        Number of checkpoints (files) saved during the run.
    checkpoint_size : int
        Number of samples per checkpoint.
    burnin : int
        Number of checkpoints to ignore as burn-in.
    save_path : str
        Directory where checkpoints are saved.
    obs_path : str
        Path to the HDF5 file with the original and observed images.
    output_file_name : str
        Name of the output JSON file (without extension).
    slices : slice, optional
        Which part of the observations to use for metrics.
    comm_size : int
        Used for distributed settings; dimension of time array.
    """

    save_path = Path(save_path)
    results_path = save_path / f"burnin_{burnin}"
    results_path.mkdir(parents=True, exist_ok=True)

    # Load time and potential data in chunks to avoid large pre-allocation
    potential_list = []
    time_list = [] if comm_size == 1 else [[] for _ in range(comm_size)]

    for i in range(n_checkpoint):
        with h5py.File(save_path / f"checkpoint_{i + 1}.h5", "r") as file:
            potential_chunk = file["potential"][:]
            potential_list.append(potential_chunk)

            time_chunk = file["computation_time"][:]
            if comm_size > 1:
                for j in range(comm_size):
                    time_list[j].append(time_chunk[j])
            else:
                time_list.append(time_chunk)

    # Concatenate once instead of pre-allocating
    potential = np.concatenate(potential_list)
    del potential_list
    gc.collect()

    if comm_size > 1:
        time = np.array([np.concatenate(time_list[j]) for j in range(comm_size)])
    else:
        time = np.concatenate(time_list)
    del time_list
    gc.collect()

    atime = (np.mean(time, axis=-1) * 1000).round(2)
    time_std = (np.std(time, axis=-1) * 1000).round(2)

    # Clear time array early
    del time
    gc.collect()

    # Load observation data
    with h5py.File(obs_path, "r") as file:
        original = file["x"][:]
        observations = file["y"][:] / obs_rg
        interpolation = file["interpolation"][:] if "interpolation" in file else None

    # Initialize MMSE accumulator
    x_mmse = np.zeros_like(original)

    # Online computation of variance using Welford's algorithm
    # This avoids storing all means and variances
    n_samples = 0
    variance_sum = np.zeros_like(original)
    mean_of_squares = np.zeros_like(original)

    for i in range(burnin, n_checkpoint):
        with h5py.File(save_path / f"checkpoint_{i + 1}.h5", "r") as file:
            mu_i = file["X_mmse"][:]
            var_i = file["X_var"][:]

            # Accumulate for MMSE
            x_mmse += mu_i

            # Online variance computation
            n_samples += 1
            delta = mu_i - (x_mmse / n_samples)  # Current estimate vs running mean
            variance_sum += var_i  # Sum of individual variances
            mean_of_squares += mu_i * mu_i  # For computing variance of means

            # Clean up immediately
            del mu_i, var_i

    # Finalize MMSE
    x_mmse /= n_checkpoint - burnin

    # Compute final variance: E[Var] + Var[E]
    # This matches the original: np.mean(variances + (means - x_mmse) ** 2, axis=0)
    avg_individual_var = variance_sum / (n_checkpoint - burnin)
    avg_squared_means = mean_of_squares / (n_checkpoint - burnin)
    variance_of_means = avg_squared_means - x_mmse * x_mmse
    x_var = avg_individual_var + variance_of_means

    # Clean up large arrays
    del (
        variance_sum,
        mean_of_squares,
        avg_individual_var,
        avg_squared_means,
        variance_of_means,
    )
    gc.collect()

    # Compute metrics (observations array can be large, so slice it for metrics only)
    obs_sliced = observations[slices]

    snr_obs = snr(original, obs_sliced)
    snr_recons = snr(original, x_mmse)
    ssim_obs = ssim(original, obs_sliced)
    ssim_recons = ssim(original, x_mmse)
    psnr_obs = psnr(original, obs_sliced)
    psnr_recons = psnr(original, x_mmse)

    # Clear observations after use
    del obs_sliced, observations
    gc.collect()

    results = {
        "mean_time_ms": atime.tolist(),
        "std_time_ms": time_std.tolist(),
        "snr_obs": round(float(snr_obs), 2),
        "psnr_obs": round(float(psnr_obs), 2),
        "ssim_obs": round(float(ssim_obs), 2),
        "snr_recons": round(float(snr_recons), 2),
        "psnr_recons": round(float(psnr_recons), 2),
        "ssim_recons": round(float(ssim_recons), 2),
    }

    if interpolation is not None:
        snr_interp = snr(original, interpolation)
        ssim_interp = ssim(original, interpolation)
        psnr_interp = psnr(original, interpolation)

        results.update(
            {
                "snr_interp": round(float(snr_interp), 2),
                "psnr_interp": round(float(psnr_interp), 2),
                "ssim_interp": round(float(ssim_interp), 2),
            }
        )

        del interpolation
        gc.collect()

    # Save results
    with open(results_path / f"{output_file_name}.json", "w") as f:
        json.dump(results, f, indent=2)

    with h5py.File(results_path / "estim.h5", "w") as f:
        f.create_dataset("x_mmse", data=x_mmse)
        f.create_dataset("x_var", data=x_var)


def power_method(
    H: Callable,
    H_adjoint: Callable,
    shape: Sequence[int],
    tol: float = 1e-4,
    max_iter: int = 300,
    rng: torch.Generator | cp.random.BitGenerator | None = None,
) -> float:
    """
    Computes the largest singular value of an operator using the power method.

    Automatically determines whether H is PyTorch-based or CuPy-based.

    Parameters
    ----------
    H : callable
        Forward operator.
    H_adjoint : callable
        Adjoint (transpose) operator.
    shape : Sequence[int]
        Shape of the input tensor.
    tol : float, optional
        Convergence tolerance (default is 1e-4).
    max_iter : int, optional
        Maximum number of iterations (default is 300).
    rng : torch.Generator | cp.random.BitGenerator, optional
        Random generator for input initialisation.

    Returns
    -------
    float
        Estimated largest singular value.
    """
    if isinstance(H, torch.nn.Module) or getattr(H, "__module__", "").startswith(
        "torch"
    ):
        xp = torch
        x = torch.rand(*shape, device=next(H.parameters()).device, generator=rng)  # type: ignore
    else:
        xp = cp
        if rng is None:
            x = cp.random.rand(*shape)
        else:
            x = rng.rand(shape)  # type: ignore

    x /= xp.linalg.norm(x)
    val = 1.0

    for _ in range(max_iter):
        old_val = val
        x = H_adjoint(H(x))
        val = xp.linalg.norm(x).item()
        if abs(val - old_val) / old_val < tol:
            break
        x /= val

    return val


def report_gpu_mem(tag=""):
    torch.cuda.synchronize()

    t_alloc = torch.cuda.memory_allocated() / 1024**2
    t_res = torch.cuda.memory_reserved() / 1024**2

    mempool = cp.get_default_memory_pool()
    cp_used = mempool.used_bytes() / 1024**2
    cupy_total = mempool.total_bytes() / 1024**2
    cp_cached = cupy_total - cp_used

    total_used = cupy_total + t_res

    print(f"\n[GPU Memory Report] {tag}")
    print(f"\tPyTorch | Alloc: {t_alloc:.2f} MB | Reserved: {t_res:.2f} MB")
    print(f"\tCuPy    | Used:  {cp_used:.2f} MB | Reserved: {cp_cached:.2f} MB")
    print(f"\tTotal   |     {total_used:.2f} MB")
