import json
import pathlib
from os.path import exists, join

import cupy as cp
import h5py
import matplotlib.pyplot as plt
import numpy as np
from skimage.metrics import structural_similarity as ssim

from mcmc.models.DistributedGaussianInpainting import DistributedGaussianInpaintingModel
from mcmc.models.GaussianInpaintingModel import GaussianInpaintingModel
from mcmc.models.GpuGaussianInpaintingModel import GpuGaussianInpaintingModel
from mcmc.sampler.DistributedSampler import DistributedSampler
from mcmc.sampler.GpuSampler import GpuSampler
from mcmc.sampler.SerialSampler import Sampler
from mcmc.slicer.cartesian_comm_slicer import CartesianCommSlicer
from mcmc.TransitionKernel.GpuTransitionKernel import GpuPSGLA
from mcmc.TransitionKernel.TransitionKernel import PSGLA


def generate_observations(original_path: str, obs_path: str) -> None:
    """generate_observations Load a signal form a .h5 file, add a gaussian noise, apply a loss operator and save the result.
    Only valid for this inpainting application.

    Parameters
    ----------
    original_path : str
        Path to the final containing the signal.
    obs_path : str
        Path to the directory where we will save the deteriorated signal.
    """
    with h5py.File(original_path) as file:
        img = np.asarray(file["x"][:])

    rng = np.random.default_rng(1234)
    sig2 = 1.75
    M, N = img.shape

    gaussian_noise = rng.normal(0, np.sqrt(sig2), (M, N))
    noised_img = img + gaussian_noise

    loss = 0.4
    mask = rng.binomial(1, 1 - loss, (M, N))
    mask_indices = np.ravel_multi_index(np.where(mask > 0), (M, N))

    observations = mask * noised_img

    with h5py.File(obs_path, "w") as file:
        file["x"] = img
        file["mask01"] = mask
        file["sig2"] = sig2
        file["data_partial"] = observations.flatten()[mask_indices]
        file["data"] = observations
        file["mask"] = mask_indices
        file["N"] = np.asarray([M, N], dtype=int)


def plot_results(
    observations: np.ndarray,
    original: np.ndarray,
    MMSE: np.ndarray,
    potential: np.ndarray,
) -> None:
    """plot_results Plot the data generated by a "compute" function : the reconstruction, the absolute error and the potential.

    Parameters
    ----------
    observations : np.ndarray
        Deteriorated signal.
    original : np.ndarray
        Original signal without any loss or noise.
    MMSE : np.ndarray
        Approximation of the original signal.
    potential : np.ndarray
        Historic of the potential for each step of the Markov chain.
    """

    pixelMin = 0.0
    pixelMax = 255

    plt.figure()
    plt.imshow(original.T, cmap="gray", vmin=pixelMin, vmax=pixelMax)
    plt.title("Truth")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(observations.T, cmap="gray", vmin=pixelMin, vmax=pixelMax)
    plt.title("Observations")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(MMSE.T, cmap="gray", vmin=pixelMin, vmax=pixelMax)
    plt.title("MMSE")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.imshow(np.abs(original.T - MMSE.T), cmap="gray")
    plt.title("Absolute error Truth/Estimator")
    plt.colorbar()
    plt.show()

    plt.figure()
    plt.plot(potential)
    plt.title("Potential")
    plt.grid()
    plt.show()


def analyze_data(
    nb_batches: int,
    burnin: int,
    save_path: str,
    data_path: str,
    output_file_name: str,
) -> None:
    """analyze_data Read the sample produced by a "compute" function and make some metrics out of it.

    Parameters
    ----------
    nb_batches : int
        Number of batches of the sample.
    burnin : int
        Number of bacth to ignore to take into account the burn-in.
    save_path : str
        Path to the directory where the sample has been saved.
    data_path : str
        Path to the file containing the deteriorated signal.
    output_file_name : str
        Full path to the file on which we will write the metrics.
    """

    potential = []
    time = []
    for i in range(1, nb_batches + 1):
        file_name = join(save_path, "sample" + str(i) + ".h5")

        with h5py.File(file_name, "r") as file:
            potential = np.append(potential, file["potential"][:])
            time = np.append(time, file["computation_time"][:])

    atime = np.mean(time)
    total_time = np.sum(time)
    time_std = np.std(time)

    with h5py.File(data_path, "r") as file:
        original = file["x"][:]
        observations = file["data"][:]

    MMSE = np.zeros(original.shape)
    for i in range(burnin, nb_batches):
        file_name = join(save_path, "sample" + str(i) + ".h5")
        with h5py.File(file_name, "r") as file:
            MMSE += file["MMSE"]
    MMSE /= nb_batches - burnin

    snr_obs = 10 * np.log10(
        np.linalg.norm(original) ** 2 / (np.linalg.norm(original - observations) ** 2)
    )

    snr_recons = 10 * np.log10(
        np.linalg.norm(original) ** 2 / (np.linalg.norm(original - MMSE) ** 2)
    )

    ssim_obs = ssim(
        original, observations, data_range=np.amax(original) - np.amin(original)
    )
    ssim_recons = ssim(original, MMSE, data_range=np.amax(original) - np.amin(original))

    results = {
        "atime": atime,
        "total_time": total_time,
        "std_time": time_std,
        "snr_obs": snr_obs,
        "snr_recons": snr_recons,
        "ssim_obs": ssim_obs,
        "ssim_recons": ssim_recons,
    }
    results_json = json.dumps(results)

    results_file = join(save_path, output_file_name + ".json")
    with open(results_file, "w") as file:
        file.write(results_json)

    plot_results(observations, original, MMSE, potential)


def load_from_h5(filename):
    """load the mask01, sig2 and data entries from the h5 file"""
    with h5py.File(filename, "r") as data_file:
        mask = data_file["mask01"][:]
        sigma2 = data_file["sig2"][()]
        observations = data_file["data"][:]
    return mask, sigma2, observations


def compute_step_size(split_coef: float, sigma2: float):
    x = 0.99 * 1.0 / (8.0 / split_coef + 1.0 / sigma2)
    z = 0.99 / split_coef
    return (x, z)


def compute_distributed(
    split_coef: float,
    reg_coef: float,
    batch_size: int,
    nb_batches: int,
    seed: int,
    save_path: str,
    data_path: str,
):
    r"""compute_distributed Generate a sample withe the distributed implementation.

    Parameters
    ----------
    split_coef : float
        Splitting coefficient, parameter of the model.
    reg_coef : float
        Regularization coefficient, parameter of the model.
    batch_size : int
        Number of iterations for a batch.
    nb_batches : int
        Number of batches of the sample.
    seed : int
        Seed.
    save_path : str
        Path to the directory where we will save the sample.
    data_path : str
        Path to the file containing the deteriorated signal.
    """
    import numpy as np
    from mpi4py import MPI

    mask, sigma2, observations = load_from_h5(data_path)
    img_size = observations.shape

    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()
    grid_size = np.asarray(MPI.Compute_dims(comm.Get_size(), 2), dtype=int)
    mpi_cart_comm = comm.Create_cart(grid_size)
    ranknd = np.asarray(mpi_cart_comm.Get_coords(rank))

    slicer = CartesianCommSlicer(
        ranknd, grid_size, observations.shape, np.asarray([0, 0]), np.asarray([0, 0])
    )
    tile_size = slicer.tile_size
    slice = slicer._get_slice_global_buffer_to_tile()
    mask = mask[slice]
    observations = observations[slice]

    step_size_X, step_size_Z = compute_step_size(split_coef, sigma2)
    X = PSGLA(tile_size, step_size_X)
    Z = PSGLA((2, *tile_size), step_size_Z)

    model = DistributedGaussianInpaintingModel(
        img_size, grid_size, observations, mask, X, Z, sigma2, reg_coef, split_coef
    )

    sampler = DistributedSampler(
        comm, batch_size, nb_batches, seed, "sample", save_path, model
    )

    sampler.sample()


def compute_gpu(
    split_coef: float,
    reg_coef: float,
    batch_size: int,
    nb_batches: int,
    seed: int,
    save_path: str,
    data_path: str,
):
    r"""compute_gpu  Generate a sample withe the implementation on GPU.

    Parameters
    ----------
    split_coef : float
        Splitting coefficient, parameter of the model.
    reg_coef : float
        Regularization coefficient, parameter of the model.
    batch_size : float
        Number of iterations for a batch.
    nb_batches : int
        Number of batches of the sample.
    seed : int
        Seed.
    save_path : str
        Path to the directory where we will save the sample.
    data_path : str
        Path to the file containing the deteriorated signal.
    """

    mask, sigma2, observations = load_from_h5(data_path)

    step_size_X, step_size_Z = compute_step_size(split_coef, sigma2)

    X = GpuPSGLA(observations.shape, step_size_X)
    Z = GpuPSGLA((2, *X.current_state.shape), step_size_Z)

    model = GpuGaussianInpaintingModel(
        cp.asarray(observations),
        cp.asarray(mask),
        X,
        Z,
        sigma2,
        reg_coef,
        split_coef,
    )

    sampler = GpuSampler(batch_size, nb_batches, seed, "sample", save_path, model)

    sampler.sample()


def compute_serial(
    split_coef: float,
    reg_coef: float,
    batch_size: int,
    nb_batches: int,
    seed: int,
    save_path: str,
    data_path: str,
):
    r"""compute_serial Generate a sample withe the serial implementation.

    Parameters
    ----------
    split_coef : float
        Splitting coefficient, parameter of the model.
    reg_coef : float
        Regularization coefficient, parameter of the model.
    batch_size : float
        Number of iterations for a batch.
    nb_batches : int
        Number of batches of the sample.
    seed : int
        Seed.
    save_path : str
        Path to the directory where we will save the sample.
    data_path : str
        Path to the file containing the deteriorated signal.
    """

    mask, sigma2, observations = load_from_h5(data_path)

    step_size_X, step_size_Z = compute_step_size(split_coef, sigma2)
    X = PSGLA(observations.shape, step_size_X)
    Z = PSGLA((2, *X.current_state.shape), step_size_Z)

    model = GaussianInpaintingModel(
        observations, mask, X, Z, sigma2, reg_coef, split_coef
    )

    sampler = Sampler(batch_size, nb_batches, seed, "sample", save_path, model)

    sampler.sample()


def main(mode, config_file_name):
    config_file = open(config_file_name)
    params = json.load(config_file)

    args = {
        "nb_batches": params["nbCheckpoint"],
        "batch_size": params["sampleSize"],
        "save_path": params["savePath"],
        "split_coef": params["alpha"],
        "reg_coef": params["regularizationCoefficient"],
        "seed": params["seed"],
        "data_path": params["dataPath"],
    }

    args_analysis = {
        "nb_batches": params["nbCheckpoint"],
        "burnin": params["burnin"],
        "save_path": params["savePath"],
        "data_path": params["dataPath"],
    }

    if not exists(args["data_path"]):
        generate_observations(params["originPath"], params["dataPath"])

    if mode == "serial":
        pathlib.Path(params["savePath"]).mkdir(parents=True, exist_ok=True)
        compute_serial(**args)
        analyze_data(**args_analysis, output_file_name="results_inpainting_serial")

    if mode == "gpu":
        pathlib.Path(params["savePath"]).mkdir(parents=True, exist_ok=True)
        compute_gpu(**args)
        analyze_data(**args_analysis, output_file_name="results_inpainting_gpu")

    if mode == "distributed":
        from mpi4py import MPI

        if MPI.COMM_WORLD.Get_rank() == 0:
            pathlib.Path(params["savePath"]).mkdir(parents=True, exist_ok=True)

        compute_distributed(**args)

        if MPI.COMM_WORLD.Get_rank() == 0:
            analyze_data(**args_analysis, output_file_name="results_inpainting_mpi")


if __name__ == "__main__":
    # main(mode="serial", config_file_name="config.json")
    main(mode="gpu", config_file_name="config.json")
    # main(mode="distributed", config_file_name="config.json")

# mpirun -n 9 python -m mpi4py main.py
